name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Deploys when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set Up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev
          docker build -t asia-southeast2-docker.pkg.dev/karim-dev404/financial-summary-api/financial-summary-api:latest .
          docker push asia-southeast2-docker.pkg.dev/karim-dev404/financial-summary-api/financial-summary-api:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy financial-summary-api \
            --image gcr.io/karim-dev404/financial-summary-api \
            --platform managed \
            --region asia-southeast2 \
            --allow-unauthenticated

